; Set session garbage collection max lifetime to 1 year (31536000 seconds)
session.gc_maxlifetime = 31536000

; Reduce garbage collection probability to very low but not zero
session.gc_probability = 1
session.gc_divisor = 10000
